name = "veneer-${CF_PAGES_BRANCH}"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-08-17"
preview_urls = true

# Bind your static output directory (e.g. the client folder SvelteKit emitted)
[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"